lib: [
  "_build/install/default/lib/ocaml_compiler/META"
  "_build/install/default/lib/ocaml_compiler/dune-package"
  "_build/install/default/lib/ocaml_compiler/lib/ocaml_compiler_lib.a" {"lib/ocaml_compiler_lib.a"}
  "_build/install/default/lib/ocaml_compiler/lib/ocaml_compiler_lib.cma" {"lib/ocaml_compiler_lib.cma"}
  "_build/install/default/lib/ocaml_compiler/lib/ocaml_compiler_lib.cmi" {"lib/ocaml_compiler_lib.cmi"}
  "_build/install/default/lib/ocaml_compiler/lib/ocaml_compiler_lib.cmt" {"lib/ocaml_compiler_lib.cmt"}
  "_build/install/default/lib/ocaml_compiler/lib/ocaml_compiler_lib.cmx" {"lib/ocaml_compiler_lib.cmx"}
  "_build/install/default/lib/ocaml_compiler/lib/ocaml_compiler_lib.cmxa" {"lib/ocaml_compiler_lib.cmxa"}
  "_build/install/default/lib/ocaml_compiler/lib/ocaml_compiler_lib.ml" {"lib/ocaml_compiler_lib.ml"}
  "_build/install/default/lib/ocaml_compiler/opam"
]
libexec: [
  "_build/install/default/lib/ocaml_compiler/lib/ocaml_compiler_lib.cmxs" {"lib/ocaml_compiler_lib.cmxs"}
]
bin: [
  "_build/install/default/bin/ocaml_compiler"
]
